apiVersion: batch/v1
kind: Job
metadata:
  name: bruce-pi
spec:
  template:
    spec:
      containers:
      - name: bruce-pi
        image: resouer/ubuntu-bc
        command: ["sh", "-c", "echo 'scale=10000; 4*a(1)' | bc -l "]
      restartPolicy: Never
  backoffLimit: 4